In [50]:
import numpy as np
import ot
import copy
import scipy as sp
import matplotlib.pylab as pl
import matplotlib.pyplot as plt
from matplotlib import image
#import ot.plot

#saves the images in 2D arrays. imgs[i-1] gives the i-th image, 
#the values are integers from 0 (white) to 255 (black)
imgs = np.fromfile('train-images.idx3-ubyte', dtype=np.uint8)
imgs = np.reshape(imgs[16:], [-1, 28, 28])

#saves the number, the picture shows in an 1D array.
labs = np.fromfile('train-labels.idx1-ubyte', dtype=np.uint8)
labs = labs[8:]

#save the indices of the numbers that are sortet.
order = [[j for j in range(0,100) if labs[j]==i] for i in range(0,10) ]

#Für die ersten 3 Bilder der Ziffern 0,1,2:

dist = np.empty((3,3,3,3,2,2))
for i in range(0,3):
    for j in range(i,3):
        for m in range(0,3):
            for n in range(m,3):
                mu = np.reshape(imgs[order[i][m]],(28*28),'C')
                nu = np.reshape(imgs[order[j][n]],(28*28),'C')
                ent = sp.stats.entropy(mu,nu)
                wd = sp.stats.wasserstein_distance(mu,nu)
                dist[i][m][j][n][0]=ent
                dist[i][m][j][n][1]=wd
print(dist)
sys.exit()

#output the first 8 images
"""
fig, axis = plt.subplots(4,4)
for i in range(0,4):
    for j in range(0,4):
        axis[i,j].imshow(imgs[i*4+j], cmap='gray')
"""
A = copy.deepcopy(imgs[0])
B = copy.deepcopy(imgs[2])

#reshape the matrix to a vector (one dim distribution) and normalize it necessary
mu = np.reshape(A,(28*28),'C')
#mu = mu/mu.sum()
nu = np.reshape(B,(28*28),'C')
#nu = nu/nu.sum()

b = np.ones((784,))
d = sp.stats.entropy(mu,b)
wd = sp.stats.wasserstein_distance(mu,nu)
print(wd)
sys.exit()


#the costfunciton is the euklidean metric on the image plane.
#the costfunciton gives the distance between the point (i*n+j)=x and y
C = np.ndarray((28*28,28*28))
for x in range(0,28*28):
    for y in range(0,28*28):
        #C[x][y]=np.linalg.norm(np.divmod(x,28)-np.divmod(y,28))
        C[x][y]=np.linalg.norm([x//28-y//28,x%28-y%28])


mu = mu.transpose()
nu = nu.transpose()
print("Dimension von mu ",mu.shape)
print("Dimension von nu ",nu.shape)
print("Dimenison von C ",C.shape)

#calculate the optimal Transport map between the both 5's
#G=ot.sinkhorn(mu.transpose(),nu.transpose(),C,0)
#T = ot.emd(mu,nu,C)

"""
print("Dimension of T",T.shape)
b = np.ones((784,))
m=np.matmul(T,b)
print(m.shape)
n=np.matmul(T.transpose(),b)
print(np.linalg.norm(np.subtract(mu,m)))
print(np.linalg.norm(np.subtract(nu,n)))
"""

#fig2, axis2 = plt.subplots()
#axis2.imshow(imgs[11],cmap='gray')

#print(imgs[0])
#print(mu)
#--------------------------------------------------------------------------------------------------

[[[[[[0.00000000e+000 0.00000000e+000]
     [0.00000000e+000 0.00000000e+000]]

    [[            inf             inf]
     [5.63010204e+000 5.63010204e+000]]

    [[            inf             inf]
     [6.96683673e+000 6.96683673e+000]]]


   [[[            inf             inf]
     [1.78061224e+001 1.78061224e+001]]

    [[            inf             inf]
     [1.71645408e+001 1.71645408e+001]]

    [[            inf             inf]
     [2.58354592e+001 2.58354592e+001]]]


   [[[            inf             inf]
     [2.19642857e+000 2.19642857e+000]]

    [[            inf             inf]
     [8.32397959e+000 8.32397959e+000]]

    [[            inf             inf]
     [1.23596939e+001 1.23596939e+001]]]]



  [[[[2.93494600e+222 5.36472736e+199]
     [4.17340004e+199 7.48269338e+247]]

    [[0.00000000e+000 0.00000000e+000]
     [0.00000000e+000 0.00000000e+000]]

    [[            inf             inf]
     [2.82142857e+000 2.82142857e+000]]]


   [[[1.94399251e-109 7.503177

SystemExit: 

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3441: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [9]:
import numpy as np
import matplotlib.pylab as pl
import matplotlib.pyplot as plt
from matplotlib import image
import ot


n = 50  # nb samples

mu_s = np.array([0, 0])
cov_s = np.array([[1, 0], [0, 1]])

mu_t = np.array([4, 4])
cov_t = np.array([[1, -.8], [-.8, 1]])

xs = ot.datasets.make_2D_samples_gauss(n, mu_s, cov_s)
xt = ot.datasets.make_2D_samples_gauss(n, mu_t, cov_t)
print(xs.shape)

a, b = np.ones((n,)) / n, np.ones((n,)) / n  # uniform distribution on samples
print(a.shape)

# loss matrix
M = ot.dist(xs, xt)
print(M.shape)

G0 = ot.emd(a, b, M)
"""
pl.figure(3)
pl.imshow(G0, interpolation='nearest')
pl.title('OT matrix G0')

pl.figure(4)
ot.plot.plot2D_samples_mat(xs, xt, G0, c=[.5, .5, 1])
pl.plot(xs[:, 0], xs[:, 1], '+b', label='Source samples')
pl.plot(xt[:, 0], xt[:, 1], 'xr', label='Target samples')
pl.legend(loc=0)
pl.title('OT matrix with samples')
"""

(50, 2)
(50,)
(50, 50)


"\npl.figure(3)\npl.imshow(G0, interpolation='nearest')\npl.title('OT matrix G0')\n\npl.figure(4)\not.plot.plot2D_samples_mat(xs, xt, G0, c=[.5, .5, 1])\npl.plot(xs[:, 0], xs[:, 1], '+b', label='Source samples')\npl.plot(xt[:, 0], xt[:, 1], 'xr', label='Target samples')\npl.legend(loc=0)\npl.title('OT matrix with samples')\n"

In [32]:
from sympy import *
import math
import sympy as sp
init_printing()
h = Symbol('h')
X=h/2*Matrix([[0,sp.sqrt(2), 0],[sp.sqrt(2),0,sp.sqrt(2)],[0,sp.sqrt(2), 0]])
Y=-I*h/2*Matrix([[0,sp.sqrt(2), 0],[-sp.sqrt(2),0,sp.sqrt(2)],[0,-sp.sqrt(2), 0]])
Z=Matrix([[h,0,0],[0,0,0],[0,0,-h]])
#pprint(X)
#pprint(Y)
#pprint(Z)
def comutator(X,Y):
    return(X*Y-Y*X)

pprint(comutator(Y,Z*Z))
#pprint(comutator(X,X*X+Y*Y+Z*Z))
#pprint(comutator(Y,X*X+Y*Y+Z*Z))
#pprint(comutator(Z,X*X+Y*Y+Z*Z))


⎡                3            ⎤
⎢          √2⋅ⅈ⋅h             ⎥
⎢   0      ───────       0    ⎥
⎢             2               ⎥
⎢                             ⎥
⎢      3                    3 ⎥
⎢√2⋅ⅈ⋅h              -√2⋅ⅈ⋅h  ⎥
⎢───────      0      ─────────⎥
⎢   2                    2    ⎥
⎢                             ⎥
⎢                3            ⎥
⎢         -√2⋅ⅈ⋅h             ⎥
⎢   0     ─────────      0    ⎥
⎣             2               ⎦
